title: "VBBSKW"
description: "Blog"
baseurl: "" 
url: "https://www.vbbskw.com"

plugins:
  - jekyll-feed

sass:
  style: compressed

# Collecties voor participatie nieuws en posts
collections:
  nieuws:
    output: true
    permalink: /nieuws/:title/
  posts2:
    output: true
    permalink: /:year/:month/:day/:title/

